### ISSUE TITLE
Update theme to use newest Sphinx Book Theme

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/sphinx-pythia-theme#39]
The newest version of Sphinx Book Theme (v0.2+) are all backwards incompatible.  We will need to make changes to the Sphinx Pythia Theme to use these new updates.  For now, the dependency on the Sphinx Book Theme is limited to versions < 0.2.

**Comment by brian-rose** [comment]
Noting here that the very cool latest tools in the MyST / Executable Books ecosystem are moving away from Sphinx entirely, e.g. https://mystmd.org/guide

Our infrastructure team should take a look at whether we want to continue to invest in Sphinx for our websites, our Cookbooks, both, or neither.

**Comment by erogluorhan** [comment]
Hey @agoose77, just wanted to let you know here, this is the issue we have been talking about Sphinx updates.

**Comment by agoose77** [comment]
Thanks @erogluorhan — is there any existing work on upgrading this theme? Just so I know where to start.

**Comment by ktyle** [comment]
@dcamron was looking into it!

**Comment by erogluorhan** [comment]
Hey @agoose77 , the actual work should be on @dcamron 's end, but just FWIW: I was playing with the things yesterday in my local and pushed them into a branch, creating a [draft PR](https://github.com/ProjectPythia/sphinx-pythia-theme/pull/58) just for the sake of showing where actions currently fail. 

You two, please feel free to take what can be helpful from that PR into your own work, take over the whole branch, or just ignore it as you see fit.

**Comment by erogluorhan** [comment]
> Hey @agoose77 , the actual work should be on @dcamron 's end, but just FWIW: I was playing with the things yesterday in my local and pushed them into a branch, creating a [draft PR](https://github.com/ProjectPythia/sphinx-pythia-theme/pull/58) just for the sake of showing where actions currently fail.
> 
> You two, please feel free to take what can be helpful from that PR into your own work, take over the whole branch and/or PR, or just ignore it as you see fit. Let me know if I can be of any help with this work.

Update: Actually, I went ahead and got the same [PR](https://github.com/ProjectPythia/sphinx-pythia-theme/pull/58) to work now as this issue is one of the highest priority infrastructure things for us currently. However, I might be missing things as this topic is not something that I have a lot of experience. I asked reviews, please give it a thorough review if you have time.

**Comment by agoose77** [comment]
@erogluorhan fast work! I was just unblocking the Jupyter book release, I'll now have time to get to this on Monday :)
