### ISSUE TITLE
Common navbar links for all themed sites

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythia/sphinx-pythia-theme#4]
We need to devise a way of specifying a common set of navbar links for all Pythia sites that use the Sphinx Pythia Theme.  The idea would be that the URLs for links in the top navbar of the Sphinx sites would all be the same, across all sites (i.e., GitHub Pages sites).

Without this feature, going to another Pythia site, even though it might use the same Sphinx Pythia Theme, the top navbar would change and there would no-longer be a common element that links all of the sites together.  And, unless I am mistaken, I think the element that *should* link all of the sites together is the top navbar.

**Comment by kmpaul** [comment]
There is a basic was of doing this in the new theme, by setting the `conf.py` options:

```
html_theme_options = {
    'nav_bar': {
        'Link A':  'URL',
        'Link B':  'URL',
        'Link C':  'URL',
    },
}
```

However, there is no guarantee that each `conf.py` has the same `html_theme_options`.

**Comment by brian-rose** [comment]
Our current solution works well and isn't too complicated.
