### ISSUE TITLE
Fix markdown title parsing on cookbooks gallery page

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/sphinx-pythia-theme#67]
![image](https://github.com/ProjectPythia/sphinx-pythia-theme/assets/24628426/af016c70-e434-4938-b142-3726176ce9e8)

somewhere between the theme updates and config at [projectpythia/cookbook-gallery](https://github.com/projectpythia/cookbook-gallery) and/or [projectpythia/projectpythia.github.io](https://github.com/projectpythia/projectpythia.github.io) our parsing of this markdown title has introduced a very professional `=============` into the gallery page. Let's find the source of this and get rid of it!

**Comment by brian-rose** [comment]
Fixed in https://github.com/ProjectPythia/cookbook-gallery/pull/205
